name: Calculadora de CI con Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '25' ]

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v5

    - name: Configurar el JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    
    - name: Compilar y ejecutar tests de la Calculadora
      run: mvn clean package

    - name: Guardar la Calculadora compilada
      uses: actions/upload-artifact@v4
      with:
        name: calculadora-app
        path: target/*.jar